# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:title

# Setup
title:            'Ahmad'
tagline:          'living since 1991'
description:      '&copy Programming,Philosophy and Bullshit.'

# Handling Reading
author:
  - facebook:     'ahmgeek'
  - twitter:      'ahmgeek'

name:           'Ahmad Abd-Elghany'
url:            'http://abdlghany.com'
email:          'ahmad@abdlghany.com'

gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
